language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - DEPS=normal
  - DEPS=highest
  - DEPS=lowest

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email: false
  slack:
    secure: SDhzL3WVQgi5zkYZ6NZBBM50ixK/IoQWlC/TDk3pxFFWmXC786L/j1ErATnITO7dXVFMo3Ex3q+PdFgmjyQcTEYWxCspRf+cxVzDNz9SHZfcDjXQtscuDyt1FfWtA6ZLXdCyIXD8cqczUTa9GJv9pwohb8Y35Vd+y8k3ZurhNxs=

before_install:
  - composer selfupdate

install:
  - if [ "$DEPS" = "normal" ]; then composer install --no-interaction; fi;
  - if [ "$DEPS" = "highest" ]; then composer update --no-interaction; fi;
  - if [ "$DEPS" = "lowest" ]; then composer update --no-interaction --prefer-lowest --prefer-stable; fi;

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - test -e build/logs/clover.xml && wget https://scrutinizer-ci.com/ocular.phar
  - test -e build/logs/clover.xml && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
